AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello World Lambda with HTTP API

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.Handler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 10
      Events:
        ApiRoot:
          Type: HttpApi
          Properties:
            Path: /
            Method: GET

